image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: npm start

vscode:
  extensions:
    - esbenp.prettier-vscode@5.9.2:/ZjVG4nabMGxTqOcyglnfQ==
    - magicstack.magicpython@1.1.1:Q+4h8/d9eu9kME/nNfIDlg==
    - batisteo.vscode-django@1.3.0:BebJLpCGbZYwexWZ2LakeQ==
    - xabikos.javascriptsnippets@1.8.0:irMtTLqQntnfBQkmtahtNA==
    - dsznajder.es7-react-js-snippets@3.1.0:MJ/bfyCCPMdDGtAC1ZzGOQ==